name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    # - windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Cache Go 1.18beta1
              id: cache-go-1-18beta1
              uses: actions/cache@v2
              with:
                  path: $HOME/go1.18beta1
                  key: ${{ runner.os }}-go1.18beta1

            - name: Install 1.18beta1
              if: steps.cache-go-1-18beta1.outputs.cache-hit != 'true'
              run: |
                  set -e
                  set -u
                  set -o pipefail

                  git clone --branch=go1.18beta1 --depth=1 https://github.com/golang/go.git $HOME/go1.18beta1
                  (cd $HOME/go1.18beta1/src && ./make.bash)

            - name: Update env
              run: |
                  set -e
                  set -u
                  set -o pipefail

                  echo "GOROOT=$HOME/go1.18beta1" >> $GITHUB_ENV
                  echo "$HOME/go1.18beta1/bin:$PATH" >> $GITHUB_PATH

            - name: Download Go dependencies
              run: go mod download

            - name: Set up Cover cmd
              run: go get golang.org/x/tools/cmd/cover

            - name: Test
              run: go test -race -covermode=atomic -coverprofile=coverage -v ./...

            - name: Codecov
              uses: codecov/codecov-action@v2
              with:
                  files: ./coverage
                  flags: unittests,${{ matrix.os }},go1.18beta1
                  fail_ci_if_error: true
                  verbose: true
