name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    # - windows-latest
                go:
                    - "1.18beta1"
        steps:
            - uses: actions/checkout@v2

            - name: Cache Go ${{ matrix.go }}
              id: cache-go-${{ matrix.go.replace('.', '-') }}
              uses: actions/cache@v2
              with:
                  path: $HOME/go${{ matrix.go }}
                  key: ${{ runner.os }}-${{ matrix.go }}

            - name: Install 1.18beta1
              if: steps.cache-go-1-18beta1.outputs.cache-hit != 'true'
              run: |
                  set -e
                  set -u
                  set -o pipefail

                  git clone --branch=go${{ matrix.go }} --depth=1 https://github.com/golang/go.git $HOME/go${{ matrix.go }}
                  (cd $HOME/go${{ matrix.go }}/src && ./make.bash)

            - name: Update env
              run: |
                  set -e
                  set -u
                  set -o pipefail

                  echo "GOROOT=$HOME/go${{ matrix.go }}" >> $GITHUB_ENV
                  echo "$HOME/go${{ matrix.go }}/bin:$PATH" >> $GITHUB_PATH

            - name: Download Go dependencies
              run: go mod download

            - name: Set up Cover cmd
              run: go get golang.org/x/tools/cmd/cover

            - name: Test
              run: go test -race -covermode=atomic -coverprofile=coverage -v ./...

            - name: Codecov
              uses: codecov/codecov-action@v2
              with:
                  files: ./coverage
                  flags: unittests,${{ matrix.os }},go${{ matrix.go }}
                  fail_ci_if_error: true
                  verbose: true
